=== 12manel123/XML-XSLT-XPath-DAW-ManelCC/XML/Creo/cancion.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


<!-- Elementos simples -->
<xs:element name="llista" type="xs:string"/>
<xs:element name="nomL" type="xs:string"/>
<xs:element name="data" type="xs:string"/>
<xs:element name="cancons" type="xs:string"/>
<xs:element name="canco" type="xs:string"/>
<xs:element name="nomC" type="xs:string"/>
<xs:element name="id" type="xs:string"/>
<xs:element name="autor" type="xs:string"/>
<xs:element name="durada" type="xs:string"/>


<!-- Elementos complex -->
<xs:element name="compte">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="llista" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nomL"/>
				<xs:element ref="data"/>
				<xs:element name="cancons">
					<xs:complexType>
						<xs:sequence>						
							<xs:element name="canco" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="nomC"/>
										<xs:element ref="id"/>
										<xs:element ref="autor"/>
										<xs:element ref="durada"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>				
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== 12manel123/XML-XSLT-XPath-DAW-ManelCC/XML/Creo/cancion.xml
<?xml version="1.0" encoding="UTF-8"?>
<compte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="cancion.xsd">
<llista>
	<nomL>Jaz</nomL>
	<data>18_11_2020</data>
	<cancons>
	<canco>
		<nomC>Karma</nomC>
		<id>1</id>
		<autor>AKR</autor>
		<durada>3:24</durada>
	</canco>
	<canco>
		<nomC>Never side</nomC>
		<id>2</id>
		<autor>Link Ronan</autor>
		<durada>3:23</durada>
	</canco>
	</cancons>
</llista>
<llista>
	<nomL>Rock</nomL>
	<data>19_12_2019</data>
	<cancons>
	<canco>
		<nomC>Blood&amp;moon</nomC>
		<id>1</id>
		<autor>Simon Nird</autor>
		<durada>3:24</durada>
	</canco>
	<canco>
		<nomC>Miare Lye</nomC>
		<id>2</id>
		<autor>Mardi Trecer</autor>
		<durada>3:23</durada>
	</canco>
	</cancons>
</llista>
</compte>
