=== 12manel123/XML-XSLT-XPath-DAW-ManelCC/XML/smartphones.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="smartphones">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="smartphone" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="operativeSystem" type="xs:string"/>
            <xs:element name="dimensions" type="xs:string"/>
            <xs:element name="weight" type="xs:string"/>
			<xs:element name="screenResolution" type="xs:string"/>
			<xs:element name="cpu" type="xs:string"/>
			<xs:element name="space" type="xs:string"/>
			<xs:element name="price" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== 12manel123/XML-XSLT-XPath-DAW-ManelCC/XML/smartphones.xml
<?xml version="1.0" encoding="UTF-8"?>
<smartphones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="smartphones.xsd">
	<smartphone>
		<name>Blackberry</name>
		<operativeSystem>Haiguay</operativeSystem>
		<dimensions>3cm,5m,2mm</dimensions>
		<weight>50kg</weight>
		<screenResolution>500px</screenResolution>
		<cpu>Intel i7 7700</cpu>
		<space>500GB</space>
		<price>690</price>
	</smartphone>
	<smartphone>
		<name>Playstation 5</name>
		<operativeSystem>Xbox Series S</operativeSystem>
		<dimensions>10km,5gm,3lm</dimensions>
		<weight>50nm</weight>
		<screenResolution>999px</screenResolution>
		<cpu>Nvidia GTX 1060 6GB</cpu>
		<space>500MB</space>
		<price>999</price>
	</smartphone>
</smartphones>
